'use client';
import {createBrowserClient} from '@supabase/ssr';
import {useState,useEffect} from 'react';
import Link from 'next/link';
export function Login({url,publicKey}:{url:string;publicKey:string}){
 const [mode,setMode]=useState<'login'|'signup'|'recover'|'reset'>('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[me,setMe]=useState<{user:{email:string};accepted:boolean}|null>(null),[accept,setAccept]=useState(false);
 const client=()=>createBrowserClient(url,publicKey);
 useEffect(()=>{fetch('/api/me',{cache:'no-store'}).then(r=>r.ok?r.json():null).then(setMe);if(location.hash.includes('type=recovery')||new URLSearchParams(location.search).get('recovery')==='1')setMode('reset');},[]);
 async function submit(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setMessage('');try{const db=client();let error;
 if(mode==='signup'){({error}=await db.auth.signUp({email,password,options:{emailRedirectTo:location.origin+'/auth/callback'}}));setMessage(error?'Não foi possível cadastrar. Verifique os dados e tente novamente.':'Confira seu e-mail para confirmar o cadastro antes de entrar.');}
 else if(mode==='recover'){({error}=await db.auth.resetPasswordForEmail(email,{redirectTo:location.origin+'/auth/callback?recovery=1'}));setMessage(error?'Não foi possível enviar o e-mail agora.':'Se a conta puder ser recuperada, você receberá um e-mail.');}
 else if(mode==='reset'){({error}=await db.auth.updateUser({password}));setMessage(error?'Não foi possível alterar a senha. Abra novamente o link recebido.':'Senha atualizada.');}
 else {({error}=await db.auth.signInWithPassword({email,password}));if(error)setMessage('Não foi possível entrar. Confira e-mail, senha e confirmação do cadastro.');else{const r=await fetch('/api/me');const data=await r.json();if(!r.ok)throw new Error(data.error);setMe(data);}}
 }catch(e){setMessage(e instanceof Error?e.message:'Serviço indisponível.');}finally{setBusy(false);}}
 async function google(){setBusy(true);try{const {error}=await client().auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+'/auth/callback'}});if(error)throw error;}catch{setMessage('Não foi possível abrir o Google. Tente novamente mais tarde.');setBusy(false);}}
 async function legal(){setBusy(true);try{const r=await fetch('/api/me',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({accepted:accept})});if(!r.ok)throw new Error();location.assign('/atlas');}catch{setMessage('Não foi possível salvar seu aceite.');setBusy(false);}}
 if(!url||!publicKey)return <div className="notice">O login ainda não está configurado neste ambiente.</div>;
 return <div className="panel">{me?<><h2>Você está conectado</h2><p>{me.user.email}</p>{!me.accepted?<><p>Antes de continuar, leia os documentos vigentes.</p><label className="check"><input type="checkbox" checked={accept} onChange={e=>setAccept(e.target.checked)}/>Li e aceito os <Link href="/legal" target="_blank">Termos de Uso e a Política de Privacidade</Link>.</label><button disabled={!accept||busy} onClick={legal}>Salvar e continuar</button></>:<Link className="primary" href="/atlas">Conversar com Atlas →</Link>}<button className="secondary" onClick={async()=>{const r=await fetch('/api/auth/logout',{method:'POST'});if(r.ok)location.assign('/login');else setMessage('Não foi possível sair. Tente novamente.');}}>Sair da conta</button></>:<><button className="google" disabled={busy} onClick={google}>Continuar com Google</button><p className="divider">ou use seu e-mail</p><form onSubmit={submit}>{mode!=='reset'&&<label>E-mail<input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label>}{mode!=='recover'&&<label>Senha<input required type="password" minLength={8} autoComplete={mode==='login'?'current-password':'new-password'} value={password} onChange={e=>setPassword(e.target.value)}/></label>}<button disabled={busy}>{busy?'Aguarde…':mode==='signup'?'Criar conta':mode==='recover'?'Enviar recuperação':mode==='reset'?'Salvar senha':'Entrar'}</button></form><div className="actions"><button className="text-button" onClick={()=>{setMode(mode==='signup'?'login':'signup');setMessage('');}}>{mode==='signup'?'Já tenho conta':'Criar uma conta'}</button><button className="text-button" onClick={()=>setMode('recover')}>Esqueci minha senha</button></div><p className="muted">O cadastro exige confirmação por e-mail.</p></>}<p role="status">{message}</p></div>;
}
