'use client';
import {useState,useEffect} from 'react';
import {shopItems,shopUrl} from '@/lib/shop';
export default function Page(){const [tab,setTab]=useState('Explorar'),[group,setGroup]=useState('Tudo'),[query,setQuery]=useState(''),[saved,setSaved]=useState<string[]>([]),[cart,setCart]=useState<string[]>([]),[ready,setReady]=useState(false),[status,setStatus]=useState('');
useEffect(()=>{try{const d=JSON.parse(localStorage.getItem('cardcraft-shop-v2')||'{}');const valid=(v:unknown)=>Array.isArray(v)?v.filter(x=>typeof x==='string'&&shopItems.some(i=>i.id===x)):[];setSaved(valid(d.saved));setCart(valid(d.cart));}catch{}setReady(true);},[]);
useEffect(()=>{if(ready)try{localStorage.setItem('cardcraft-shop-v2',JSON.stringify({saved,cart}));}catch{setStatus('Seu navegador não permitiu salvar as listas. Elas durarão apenas nesta visita.');}},[ready,saved,cart]);
const toggle=(id:string,type:'cart'|'saved')=>{const setter=type==='cart'?setCart:setSaved;setter(a=>a.includes(id)?a.filter(x=>x!==id):[...a,id]);};
const shown=shopItems.filter(i=>(group==='Tudo'||i.group===group)&&(i.name+' '+i.game).toLowerCase().includes(query.toLowerCase())&&(tab==='Explorar'||(tab==='Desejos'?saved:cart).includes(i.id)));
return <main className="page"><section className="shop-hero"><span className="eyebrow">CARDCRAFT SHOP</span><h1>Seu próximo achado<br/><em>começa aqui.</em></h1><p>Explore cartas, lacrados e acessórios. Salve suas escolhas e compare nas lojas.</p></section><div className="tabs">{['Explorar','Desejos','Carrinho de links'].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t} {t==='Desejos'?`(${saved.length})`:t==='Carrinho de links'?`(${cart.length})`:''}</button>)}</div><p className="notice">Organizamos links comuns de busca. O CardCraftAI não vende estes produtos nem recebe o pagamento. As listas ficam neste navegador; preços e disponibilidade são definidos pelas lojas.</p><div className="shop-filters"><label>Buscar<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Jogo, carta ou acessório"/></label><label>Categoria<select value={group} onChange={e=>setGroup(e.target.value)}>{['Tudo','Cartas','Lacrados','Acessórios'].map(g=><option key={g}>{g}</option>)}</select></label></div><p role="status">{status}</p><div className="shop-grid">{shown.map(i=><article className="panel shop-card" key={i.id}><div className="product-art" aria-hidden="true">{i.icon}</div><span className="eyebrow">{i.group}</span><h2>{i.name}</h2><p className="muted">Explore opções nas lojas. Sem preço ou estoque prometido.</p><div className="actions"><button className="secondary" aria-pressed={saved.includes(i.id)} onClick={()=>toggle(i.id,'saved')}>{saved.includes(i.id)?'♥ Salvo':'♡ Desejar'}</button><button onClick={()=>toggle(i.id,'cart')}>{cart.includes(i.id)?'Remover do carrinho':'+ Carrinho'}</button></div><div className="actions"><a href={shopUrl(i.query,'tcgplayer')} target="_blank" rel="noopener noreferrer">TCGplayer ↗</a><a href={shopUrl(i.query,'amazon')} target="_blank" rel="noopener noreferrer">Amazon Brasil ↗</a></div></article>)}</div>{!shown.length&&<p className="panel">Nenhuma escolha por aqui. Explore as categorias para adicionar itens.</p>}</main>;}
