-- CardCraft Catalog Core
-- Canonical, provenance-aware internal catalog. Applied first to CardCraftAI-TEST.
-- Runtime reads our database; external sources are synchronization inputs, not the product source of truth.

create extension if not exists pg_trgm;

create table if not exists public.catalog_games (
  slug text primary key,
  name text not null,
  publisher text not null default '',
  active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint catalog_games_slug_format check (slug ~ '^[a-z0-9][a-z0-9-]{1,39}$')
);

create table if not exists public.catalog_sources (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  homepage text not null default '',
  source_type text not null,
  license_name text not null default '',
  license_url text not null default '',
  redistribution_mode text not null default 'review',
  attribution_text text not null default '',
  active boolean not null default true,
  terms_verified_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint catalog_sources_code_format check (code ~ '^[a-z0-9][a-z0-9_-]{1,39}$'),
  constraint catalog_sources_type_check check (source_type in ('repository','api','official','community','manual')),
  constraint catalog_sources_redistribution_check check (redistribution_mode in ('mirror_allowed','metadata_allowed','reference_only','review'))
);

create table if not exists public.catalog_sets (
  id uuid primary key default gen_random_uuid(),
  game_slug text not null references public.catalog_games(slug) on delete restrict,
  canonical_key text not null unique,
  code text not null default '',
  name text not null,
  name_search text not null,
  series text not null default '',
  release_date date,
  printed_total integer,
  total integer,
  region text not null default '',
  status text not null default 'active',
  source_count integer not null default 0,
  attributes jsonb not null default '{}'::jsonb,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint catalog_sets_status_check check (status in ('active','unverified','retired'))
);

create table if not exists public.catalog_cards (
  id uuid primary key default gen_random_uuid(),
  game_slug text not null references public.catalog_games(slug) on delete restrict,
  set_id uuid references public.catalog_sets(id) on delete set null,
  canonical_key text not null unique,
  collector_number text not null default '',
  local_id text not null default '',
  category text not null default '',
  rarity text not null default '',
  illustrator text not null default '',
  hp integer,
  dex_ids integer[] not null default '{}',
  release_date date,
  status text not null default 'active',
  verification_status text not null default 'source_verified',
  data_quality smallint not null default 50,
  source_count integer not null default 0,
  attributes jsonb not null default '{}'::jsonb,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint catalog_cards_status_check check (status in ('active','unverified','retired')),
  constraint catalog_cards_verification_check check (verification_status in ('source_verified','multi_source','community_verified','pending_review')),
  constraint catalog_cards_quality_check check (data_quality between 0 and 100)
);

create table if not exists public.catalog_card_localizations (
  id uuid primary key default gen_random_uuid(),
  card_id uuid not null references public.catalog_cards(id) on delete cascade,
  language text not null,
  name text not null,
  name_search text not null,
  description text not null default '',
  rules jsonb not null default '{}'::jsonb,
  image_url text not null default '',
  image_small_url text not null default '',
  image_status text not null default 'remote_reference',
  source_count integer not null default 0,
  attributes jsonb not null default '{}'::jsonb,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(card_id, language),
  constraint catalog_card_localizations_language_check check (language ~ '^[a-z]{2,3}(-[a-z0-9]{2,8})?$'),
  constraint catalog_card_localizations_image_status_check check (image_status in ('remote_reference','local_cached','unavailable','rights_review'))
);

create table if not exists public.catalog_card_variants (
  id uuid primary key default gen_random_uuid(),
  card_id uuid not null references public.catalog_cards(id) on delete cascade,
  variant_key text not null,
  variant_type text not null default 'normal',
  subtype text not null default '',
  size text not null default 'standard',
  stamps text[] not null default '{}',
  external_ids jsonb not null default '{}'::jsonb,
  attributes jsonb not null default '{}'::jsonb,
  verification_status text not null default 'source_verified',
  source_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(card_id, variant_key),
  constraint catalog_card_variants_verification_check check (verification_status in ('source_verified','multi_source','community_verified','pending_review'))
);

create table if not exists public.catalog_aliases (
  id bigint generated by default as identity primary key,
  card_id uuid not null references public.catalog_cards(id) on delete cascade,
  language text not null default 'und',
  alias text not null,
  alias_search text not null,
  alias_type text not null default 'name',
  source_id bigint references public.catalog_sources(id) on delete set null,
  created_at timestamptz not null default now(),
  unique(card_id, language, alias_search, alias_type)
);

create table if not exists public.catalog_source_records (
  id uuid primary key default gen_random_uuid(),
  source_id bigint not null references public.catalog_sources(id) on delete cascade,
  source_key text not null,
  language text not null default 'und',
  entity_type text not null default 'card',
  payload_hash text not null,
  payload jsonb not null default '{}'::jsonb,
  source_updated_at timestamptz,
  fetched_at timestamptz not null default now(),
  unique(source_id, source_key, language, entity_type),
  constraint catalog_source_records_entity_check check (entity_type in ('game','set','card','variant','price_reference'))
);

create table if not exists public.catalog_source_links (
  id bigint generated by default as identity primary key,
  source_id bigint not null references public.catalog_sources(id) on delete cascade,
  source_key text not null,
  language text not null default 'und',
  card_id uuid references public.catalog_cards(id) on delete cascade,
  set_id uuid references public.catalog_sets(id) on delete cascade,
  variant_id uuid references public.catalog_card_variants(id) on delete cascade,
  confidence smallint not null default 100,
  field_coverage jsonb not null default '{}'::jsonb,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  unique(source_id, source_key, language, card_id, set_id, variant_id),
  constraint catalog_source_links_confidence_check check (confidence between 0 and 100),
  constraint catalog_source_links_target_check check (card_id is not null or set_id is not null or variant_id is not null)
);

create table if not exists public.catalog_sync_runs (
  id uuid primary key default gen_random_uuid(),
  source_id bigint not null references public.catalog_sources(id) on delete restrict,
  mode text not null default 'incremental',
  status text not null default 'running',
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  discovered_count integer not null default 0,
  inserted_count integer not null default 0,
  updated_count integer not null default 0,
  conflict_count integer not null default 0,
  error_count integer not null default 0,
  source_revision text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  constraint catalog_sync_runs_mode_check check (mode in ('inventory','hydrate','incremental','full_rebuild','manual')),
  constraint catalog_sync_runs_status_check check (status in ('running','completed','partial','failed'))
);

create table if not exists public.catalog_conflicts (
  id uuid primary key default gen_random_uuid(),
  card_id uuid references public.catalog_cards(id) on delete cascade,
  field_name text not null,
  current_value jsonb,
  candidate_value jsonb,
  current_source_id bigint references public.catalog_sources(id) on delete set null,
  candidate_source_id bigint references public.catalog_sources(id) on delete set null,
  status text not null default 'open',
  resolution_note text not null default '',
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  constraint catalog_conflicts_status_check check (status in ('open','accepted_candidate','kept_current','merged','dismissed'))
);

create table if not exists public.catalog_discovery_submissions (
  id uuid primary key default gen_random_uuid(),
  submitted_by uuid not null references auth.users(id) on delete cascade,
  game_slug text not null references public.catalog_games(slug) on delete restrict,
  claimed_name text not null,
  claimed_set text not null default '',
  claimed_number text not null default '',
  claimed_language text not null default '',
  claimed_variant text not null default '',
  evidence_notes text not null default '',
  evidence_urls text[] not null default '{}',
  status text not null default 'pending',
  matched_card_id uuid references public.catalog_cards(id) on delete set null,
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  review_note text not null default '',
  constraint catalog_discovery_status_check check (status in ('pending','needs_evidence','accepted','duplicate','rejected')),
  constraint catalog_discovery_notes_length check (char_length(evidence_notes) <= 4000)
);

create index if not exists catalog_sets_game_code_idx on public.catalog_sets(game_slug, code);
create index if not exists catalog_sets_name_trgm_idx on public.catalog_sets using gin (name_search gin_trgm_ops);
create index if not exists catalog_cards_game_set_number_idx on public.catalog_cards(game_slug, set_id, collector_number);
create index if not exists catalog_cards_status_idx on public.catalog_cards(game_slug, status);
create index if not exists catalog_card_localizations_name_trgm_idx on public.catalog_card_localizations using gin (name_search gin_trgm_ops);
create index if not exists catalog_card_localizations_lang_idx on public.catalog_card_localizations(language, card_id);
create index if not exists catalog_card_variants_card_idx on public.catalog_card_variants(card_id);
create index if not exists catalog_aliases_trgm_idx on public.catalog_aliases using gin (alias_search gin_trgm_ops);
create index if not exists catalog_source_links_card_idx on public.catalog_source_links(card_id);
create index if not exists catalog_source_links_set_idx on public.catalog_source_links(set_id);
create index if not exists catalog_source_records_lookup_idx on public.catalog_source_records(source_id, source_key, language);
create index if not exists catalog_discovery_user_idx on public.catalog_discovery_submissions(submitted_by, created_at desc);
create index if not exists catalog_conflicts_open_idx on public.catalog_conflicts(status, created_at desc);

alter table public.catalog_games enable row level security;
alter table public.catalog_sources enable row level security;
alter table public.catalog_sets enable row level security;
alter table public.catalog_cards enable row level security;
alter table public.catalog_card_localizations enable row level security;
alter table public.catalog_card_variants enable row level security;
alter table public.catalog_aliases enable row level security;
alter table public.catalog_source_records enable row level security;
alter table public.catalog_source_links enable row level security;
alter table public.catalog_sync_runs enable row level security;
alter table public.catalog_conflicts enable row level security;
alter table public.catalog_discovery_submissions enable row level security;

revoke all on table public.catalog_games from anon, authenticated;
revoke all on table public.catalog_sources from anon, authenticated;
revoke all on table public.catalog_sets from anon, authenticated;
revoke all on table public.catalog_cards from anon, authenticated;
revoke all on table public.catalog_card_localizations from anon, authenticated;
revoke all on table public.catalog_card_variants from anon, authenticated;
revoke all on table public.catalog_aliases from anon, authenticated;
revoke all on table public.catalog_source_records from anon, authenticated;
revoke all on table public.catalog_source_links from anon, authenticated;
revoke all on table public.catalog_sync_runs from anon, authenticated;
revoke all on table public.catalog_conflicts from anon, authenticated;
revoke all on table public.catalog_discovery_submissions from anon, authenticated;

grant select on table public.catalog_games to authenticated;
grant select on table public.catalog_sources to authenticated;
grant select on table public.catalog_sets to authenticated;
grant select on table public.catalog_cards to authenticated;
grant select on table public.catalog_card_localizations to authenticated;
grant select on table public.catalog_card_variants to authenticated;
grant select on table public.catalog_aliases to authenticated;
grant insert, select on table public.catalog_discovery_submissions to authenticated;

drop policy if exists catalog_games_read on public.catalog_games;
create policy catalog_games_read on public.catalog_games for select to authenticated using (active = true);
drop policy if exists catalog_sources_read on public.catalog_sources;
create policy catalog_sources_read on public.catalog_sources for select to authenticated using (active = true);
drop policy if exists catalog_sets_read on public.catalog_sets;
create policy catalog_sets_read on public.catalog_sets for select to authenticated using (status in ('active','unverified'));
drop policy if exists catalog_cards_read on public.catalog_cards;
create policy catalog_cards_read on public.catalog_cards for select to authenticated using (status in ('active','unverified'));
drop policy if exists catalog_localizations_read on public.catalog_card_localizations;
create policy catalog_localizations_read on public.catalog_card_localizations for select to authenticated using (true);
drop policy if exists catalog_variants_read on public.catalog_card_variants;
create policy catalog_variants_read on public.catalog_card_variants for select to authenticated using (true);
drop policy if exists catalog_aliases_read on public.catalog_aliases;
create policy catalog_aliases_read on public.catalog_aliases for select to authenticated using (true);
drop policy if exists catalog_discovery_insert_own on public.catalog_discovery_submissions;
create policy catalog_discovery_insert_own on public.catalog_discovery_submissions
for insert to authenticated with check ((select auth.uid()) is not null and submitted_by = (select auth.uid()));
drop policy if exists catalog_discovery_read_own on public.catalog_discovery_submissions;
create policy catalog_discovery_read_own on public.catalog_discovery_submissions
for select to authenticated using ((select auth.uid()) is not null and submitted_by = (select auth.uid()));

insert into public.catalog_games(slug,name,publisher,active,metadata)
values
  ('pokemon','Pokémon Trading Card Game','The Pokémon Company',true,'{"catalog_family":"physical"}'::jsonb),
  ('pokemon-pocket','Pokémon TCG Pocket','The Pokémon Company',true,'{"catalog_family":"digital"}'::jsonb),
  ('mtg','Magic: The Gathering','Wizards of the Coast',true,'{}'::jsonb),
  ('yugioh','Yu-Gi-Oh!','Konami',true,'{}'::jsonb),
  ('digimon','Digimon Card Game','Bandai',true,'{}'::jsonb),
  ('lorcana','Disney Lorcana','Ravensburger',true,'{}'::jsonb),
  ('one-piece','One Piece Card Game','Bandai',true,'{}'::jsonb)
on conflict (slug) do update
set name=excluded.name,publisher=excluded.publisher,active=excluded.active,updated_at=now();

insert into public.catalog_sources(
  code,name,homepage,source_type,license_name,license_url,redistribution_mode,
  attribution_text,active,terms_verified_at,metadata
)
values (
  'tcgdex','TCGdex cards-database','https://github.com/tcgdex/cards-database',
  'repository','MIT','https://github.com/tcgdex/cards-database/blob/master/LICENSE',
  'mirror_allowed',
  'Card metadata derived from TCGdex cards-database (MIT). TCGdex is not affiliated with Nintendo or The Pokémon Company.',
  true,now(),'{"games":["pokemon","pokemon-pocket"],"preferred_ingest":"repository","images":"reference_only"}'::jsonb
),(
  'cardcraft-community','CardCraft Community discoveries','','community',
  'CardCraftAI internal','','metadata_allowed',
  'Community-submitted discoveries require review before becoming canonical catalog records.',
  true,now(),'{"workflow":"review_required"}'::jsonb
)
on conflict (code) do update set
  name=excluded.name,homepage=excluded.homepage,license_name=excluded.license_name,
  license_url=excluded.license_url,redistribution_mode=excluded.redistribution_mode,
  attribution_text=excluded.attribution_text,active=excluded.active,
  terms_verified_at=excluded.terms_verified_at,metadata=excluded.metadata,updated_at=now();

create or replace function public.search_catalog_core(
  p_query text,
  p_game_slug text default null,
  p_language text default null,
  p_limit integer default 40
)
returns table (
  card_id uuid, game_slug text, set_id uuid, set_code text, set_name text,
  collector_number text, rarity text, illustrator text, language text,
  card_name text, image_url text, image_small_url text,
  verification_status text, source_count integer, rank_score real
)
language sql
stable
security invoker
set search_path = public
as $$
  with q as (select lower(btrim(coalesce(p_query,''))) as value),
  ranked as (
    select c.id as card_id,c.game_slug,c.set_id,coalesce(s.code,'') as set_code,
      coalesce(s.name,'') as set_name,c.collector_number,c.rarity,c.illustrator,
      l.language,l.name as card_name,l.image_url,l.image_small_url,
      c.verification_status,c.source_count,
      greatest(
        case when lower(l.name_search)=q.value then 1.0
             when lower(l.name_search) like q.value||'%' then 0.95
             when lower(l.name_search) like '%'||q.value||'%' then 0.85
             else similarity(lower(l.name_search),q.value) end,
        similarity(lower(coalesce(s.name_search,'')),q.value),
        similarity(lower(coalesce(c.collector_number,'')),q.value)
      )::real as rank_score
    from public.catalog_cards c
    join public.catalog_card_localizations l on l.card_id=c.id
    left join public.catalog_sets s on s.id=c.set_id
    cross join q
    where c.status in ('active','unverified')
      and (p_game_slug is null or c.game_slug=p_game_slug)
      and (p_language is null or l.language=p_language)
      and (
        lower(l.name_search) % q.value
        or lower(l.name_search) like '%'||q.value||'%'
        or lower(coalesce(s.name_search,'')) % q.value
        or lower(coalesce(c.collector_number,'')) like '%'||q.value||'%'
      )
  )
  select * from ranked
  where rank_score >= 0.18
  order by rank_score desc,card_name,set_name,collector_number
  limit greatest(1,least(coalesce(p_limit,40),100));
$$;

revoke all on function public.search_catalog_core(text,text,text,integer) from public, anon;
grant execute on function public.search_catalog_core(text,text,text,integer) to authenticated;
