'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
type Item={id:string;catalog_id:string;card_name:string;quantity:number;condition:string;variant:string;language:string;notes:string;wishlist:boolean};
export default function Page(){const [items,setItems]=useState<Item[]>([]),[page,setPage]=useState(0),[total,setTotal]=useState(0),[status,setStatus]=useState('Carregando…'),[edit,setEdit]=useState<Item|null>(null),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0);
useEffect(()=>{const c=new AbortController();setStatus('Carregando…');fetch('/api/collection?page='+page,{signal:c.signal,cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setItems(d.items);setTotal(d.total);setStatus('');}).catch(e=>{if(!c.signal.aborted){setItems([]);setStatus(e.message);}});return()=>c.abort();},[page,refresh]);
async function save(e:React.FormEvent){e.preventDefault();if(!edit)return;setBusy(true);try{const r=await fetch('/api/collection',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...edit,before:items.find(i=>i.id===edit.id)})});const d=await r.json();if(!r.ok)throw new Error(d.error);setEdit(null);setRefresh(n=>n+1);}catch(e){setStatus(e instanceof Error?e.message:'Falha ao salvar.');}finally{setBusy(false);}}
async function remove(id:string){if(!confirm('Remover esta entrada da sua coleção?'))return;setBusy(true);try{const r=await fetch('/api/collection',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});if(!r.ok)throw new Error();setRefresh(n=>n+1);}catch{setStatus('Não foi possível remover.');}finally{setBusy(false);}}
return <main className="page"><span className="eyebrow">CADA DESCOBERTA, NO SEU LUGAR</span><h1>Minha coleção</h1><p>Cartas, quantidades, condições e desejos vinculados à sua conta.</p><div className="actions"><Link className="primary" href="/catalogo">Adicionar cartas →</Link><Link href="/login">Minha conta</Link></div><p className="notice">Valor de mercado: indisponível. Nenhum preço é estimado sem fonte, edição, condição e data verificáveis.</p><p role="status">{status}</p>{!status&&<p>{total} entradas · página {page+1}</p>}<div className="collection-grid">{items.map(i=><article className="panel" key={i.id}><Link href={'/catalogo/'+encodeURIComponent(i.catalog_id)}><h2>{i.card_name}</h2></Link><p>{i.catalog_id} · {i.wishlist?'Na lista de desejos':`${i.quantity} unidade(s)`}</p><p>{i.condition} · {i.language} · {i.variant||'Variante não informada'}</p><div className="actions"><button onClick={()=>setEdit({...i})}>Editar</button><button className="secondary" disabled={busy} onClick={()=>remove(i.id)}>Remover</button></div></article>)}</div>{!status&&!items.length&&<div className="panel">Sua coleção ainda não tem cartas nesta página. Explore o catálogo para começar.</div>}<div className="actions"><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>Anterior</button><button disabled={(page+1)*48>=total} onClick={()=>setPage(p=>p+1)}>Próxima</button></div>{edit&&<div className="modal"><section className="panel" role="dialog" aria-modal="true" aria-label="Editar carta"><h2>{edit.card_name}</h2><form onSubmit={save}><label>Quantidade<input type="number" min="0" max="9999" required value={edit.quantity} onChange={e=>setEdit({...edit,quantity:Number(e.target.value)})}/></label><label>Condição<select value={edit.condition} onChange={e=>setEdit({...edit,condition:e.target.value})}>{['Not assessed','Near Mint','Lightly Played','Moderately Played','Heavily Played','Damaged'].map(c=><option key={c}>{c}</option>)}</select></label><label>Idioma<input maxLength={80} value={edit.language} onChange={e=>setEdit({...edit,language:e.target.value})}/></label><label>Variante<input maxLength={120} value={edit.variant} onChange={e=>setEdit({...edit,variant:e.target.value})}/></label><label>Notas<textarea maxLength={2000} value={edit.notes} onChange={e=>setEdit({...edit,notes:e.target.value})}/></label><label className="check"><input type="checkbox" checked={edit.wishlist} onChange={e=>setEdit({...edit,wishlist:e.target.checked})}/>Lista de desejos</label><p role="status">{status}</p><div className="actions"><button disabled={busy}>Salvar</button><button type="button" className="secondary" onClick={()=>setEdit(null)}>Cancelar</button></div></form></section></div>}</main>;}
